/*
CREATE DATABASE Bruno_DB;

USE Bruno_DB;

CREATE TABLE Sensor(
	id INT PRIMARY KEY IDENTITY,
	Temperatura FLOAT NULL,
	Umidade INT NULL,
	timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
*/

SELECT * FROM Sensor;
